### ISSUE TITLE
compilation warning "WARNING: API 'variant.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'. It will be removed at the end of 2019"

### ISSUE THREAD

**Issue by pickeyboy** [jaredsburrows/gradle-spoon-plugin#76] opened 2020-02-03 23:26 UTC

**Comment by ZakTaccardi** [comment] 2020-03-03 23:31
duplicate of #77, this can be closed

**Closed** 2020-03-04 00:34 UTC
