### ISSUE TITLE
variantOutput depreciation 

### ISSUE THREAD

**Issue by shareme** [jaredsburrows/gradle-spoon-plugin#51] opened 2019-01-12 16:22 UTC
I get this warning when applying your 1.5.0 plugin using gradle 5.1 and the android plpugin version is 3.4 alpha10

WARNING: API 'variantOutput.getPackageApplication()' is obsolete and has been replaced with 'variant.getPackageApplicationProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getPackageApplication(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: app

**Comment by vladad** [comment] 2019-01-28 08:32
This is duplicate of my earlier issue #48

**Comment by jaredsburrows** [comment] 2019-01-29 02:38
Thank you @shareme and @vladad.

**Closed by jaredsburrows** 2019-01-29 02:38 UTC
